-- Empty PostgreSQL schema. No patient data is seeded.
CREATE TABLE IF NOT EXISTS patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    dob DATE NOT NULL,
    gender VARCHAR(1) NOT NULL CHECK (gender IN ('M', 'F', 'O')),
    mrn VARCHAR(30) NOT NULL UNIQUE,
    diagnosis VARCHAR(255) NOT NULL DEFAULT '',
    assigned_to VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_patients_assigned_to
    ON patients (assigned_to, id);

ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE patients FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS patients_subject_policy ON patients;
CREATE POLICY patients_subject_policy ON patients
    USING (
        current_setting('app.role', true) = 'admin'
        OR assigned_to = current_setting('app.subject_id', true)
    )
    WITH CHECK (assigned_to = current_setting('app.subject_id', true));

CREATE TABLE IF NOT EXISTS audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_sub VARCHAR(255) NOT NULL,
    action VARCHAR(64) NOT NULL,
    resource_type VARCHAR(32) NOT NULL,
    resource_id VARCHAR(64),
    source_ip INET,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_events_actor_time
    ON audit_events (actor_sub, occurred_at DESC);

ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_events FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS audit_actor_policy ON audit_events;
CREATE POLICY audit_actor_policy ON audit_events
    WITH CHECK (actor_sub = current_setting('app.subject_id', true));
