-- MediGuard Database Initialisation
-- ALL patient data below is ENTIRELY FAKE, generated by db/seed_faker.py using the Faker library.
-- NO real patient data is used at any point in this project.

CREATE DATABASE IF NOT EXISTS mediguard_db;
USE mediguard_db;

CREATE TABLE IF NOT EXISTS patients (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(150)      NOT NULL,
    dob         DATE              NOT NULL,
    gender      ENUM('M','F','O') NOT NULL,
    mrn         VARCHAR(30)       UNIQUE NOT NULL COMMENT 'Medical Record Number (FAKE)',
    diagnosis   VARCHAR(255),
    assigned_to VARCHAR(100)      COMMENT 'Clinician username',
    created_at  TIMESTAMP         DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS app_users (
    id            INT AUTO_INCREMENT PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'clinician',
    created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS prediction_history (
    id               INT AUTO_INCREMENT PRIMARY KEY,
    username         VARCHAR(50) NOT NULL,
    features         JSON        NOT NULL,
    prediction       TINYINT     NOT NULL,
    risk_probability DECIMAL(6, 4) NOT NULL,
    risk_label       VARCHAR(10) NOT NULL,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_prediction_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── FAKE seed data (generated by Faker, not real patients) ────────────────────
INSERT INTO patients (name, dob, gender, mrn, diagnosis, assigned_to) VALUES
  ('Patrick Sanchez',   '1984-04-08', 'M', 'MRN-770487', 'Hypertension Stage 1',              'clinician'),
  ('Megan Mcclain',     '1950-04-02', 'M', 'MRN-356787', 'Coronary Artery Disease',            'admin'),
  ('Amanda Davis',      '1946-09-02', 'O', 'MRN-809570', 'Type 2 Diabetes with Cardiac Risk',  'admin'),
  ('Alyssa Gonzalez',   '1956-08-02', 'F', 'MRN-719176', 'Hypertension Stage 1',              'admin'),
  ('Jennifer Cole',     '1984-12-23', 'M', 'MRN-198246', 'Atrial Fibrillation',               'admin'),
  ('Abigail Shaffer',   '1959-09-08', 'M', 'MRN-688508', 'Type 2 Diabetes with Cardiac Risk',  'clinician'),
  ('Donald Lewis',      '1988-04-06', 'F', 'MRN-331148', 'Arrhythmia - paroxysmal',           'clinician'),
  ('Brandon Davis',     '1992-09-16', 'M', 'MRN-948749', 'Coronary Artery Disease',            'clinician'),
  ('Renee Blair',       '1964-02-29', 'F', 'MRN-456778', 'Coronary Artery Disease',            'admin'),
  ('Thomas Miller',     '1977-03-31', 'F', 'MRN-900581', 'Hypertension Stage 2',              'admin'),
  ('Lisa Hensley',      '1960-09-14', 'M', 'MRN-498382', 'Stable Angina',                     'clinician'),
  ('Benjamin Stanley',  '1980-01-17', 'F', 'MRN-733052', 'Hypertension Stage 1',              'clinician'),
  ('Bobby Hall',        '1993-05-12', 'M', 'MRN-662275', 'Myocardial Infarction History',      'admin'),
  ('Jesse Flowers',     '1947-08-18', 'F', 'MRN-678856', 'Arrhythmia - paroxysmal',           'clinician'),
  ('Sara Torres',       '1975-06-21', 'F', 'MRN-554321', 'Heart Failure (EF preserved)',       'clinician'),
  ('Marcus Webb',       '1962-11-05', 'M', 'MRN-223456', 'Hyperlipidaemia',                   'admin'),
  ('Diana Prince',      '1990-07-14', 'F', 'MRN-889012', 'Stable Angina',                     'clinician'),
  ('Kevin Okafor',      '1955-03-29', 'M', 'MRN-334567', 'Coronary Artery Disease',            'admin'),
  ('Priya Sharma',      '1980-09-11', 'F', 'MRN-445678', 'Hypertension Stage 2',              'clinician'),
  ('Omar Hassan',       '1970-01-22', 'M', 'MRN-556789', 'Atrial Fibrillation',               'admin');
