"""
db/seed_faker.py – Generate FAKE patient seed data using the Faker library.

Run: python db/seed_faker.py > db/fake_patients.sql

All names, dates of birth, and MRNs are entirely fictional.
NO real patient data is used anywhere in this project.
"""

from __future__ import annotations

import random
import sys
from datetime import date

from faker import Faker

fake = Faker("en_US")
random.seed(42)
Faker.seed(42)

DIAGNOSES = [
    "Hypertension Stage 1",
    "Hypertension Stage 2",
    "Coronary Artery Disease",
    "Atrial Fibrillation",
    "Heart Failure (EF preserved)",
    "Stable Angina",
    "Myocardial Infarction History",
    "Hyperlipidaemia",
    "Type 2 Diabetes with Cardiac Risk",
    "Arrhythmia – paroxysmal",
]
GENDERS = ["M", "F", "O"]
CLINICIANS = ["admin", "clinician"]
N_PATIENTS = 50


def generate_patients(n: int = N_PATIENTS) -> list[dict]:
    patients = []
    mrns = set()
    for i in range(n):
        # Unique MRN
        while True:
            mrn = f"MRN-{random.randint(100000, 999999)}"
            if mrn not in mrns:
                mrns.add(mrn)
                break
        dob = fake.date_of_birth(minimum_age=30, maximum_age=85)
        patients.append({
            "name": fake.name(),
            "dob": dob.isoformat(),
            "gender": random.choice(GENDERS),
            "mrn": mrn,
            "diagnosis": random.choice(DIAGNOSES),
            "assigned_to": random.choice(CLINICIANS),
        })
    return patients


def to_sql(patients: list[dict]) -> str:
    lines = [
        "-- FAKE patient seed data generated by db/seed_faker.py using Faker library.",
        "-- No real patient data. For educational purposes only.",
        "USE mediguard_db;",
        "DELETE FROM patients;",
        "",
        "INSERT INTO patients (name, dob, gender, mrn, diagnosis, assigned_to) VALUES",
    ]
    value_rows = []
    for p in patients:
        name = p["name"].replace("'", "''")
        value_rows.append(
            f"  ('{name}', '{p['dob']}', '{p['gender']}', "
            f"'{p['mrn']}', '{p['diagnosis']}', '{p['assigned_to']}')"
        )
    lines.append(",\n".join(value_rows) + ";")
    return "\n".join(lines)


if __name__ == "__main__":
    patients = generate_patients()
    sql = to_sql(patients)
    print(sql)
